name: Rust Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cargo-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Run Rust tests
        run: cd src-tauri && cargo test --all-features
